### PR TITLE
OGG Vorbis Music Patches

### PR DESCRIPTION
**Pull request by colbyshores**
This contains patches for ogg vorbis playback.  Each .ogg track is stored in a folder called data/sound/music and there is also a file that is called music.dat
music.dat is a text file containing the track listing where
level1 is the first line, level2 is the second line, etc

for example:

track1

track2

track3

track4

where track1 is level1, track2 is level2 and so on.

the preconfigured tracks and mapping can be downloaded here
https://drive.google.com/open?id=0B4z9LMg7J5EYTlltSVhwNmNuNzg

### CODE REVIEW

**Comment by chino** [comment]
I must have missed the email alert for this pull request and haven't noticed till now.

The code looks pretty simple so it should be easy for us to merge this in :]

**Comment by willkillson** [comment]
@chino Hey mate, some people were asking about this in discord. I am sure you are busy, are you still interested in this MR?

**Comment by chino** [comment]
Some quick notes looking over this.

The `music.c` file looks pretty great so thanks for that.

Needs a full rebase/squash:
- changes to `$(LUA)` in makefile need to be backed out
- as well as changes to `net_enet_2.c` shouldn't be included in this
- it contains an entire copy of the pandora work which shouldn't be here
- there is a binary files accidently added/deleted in the commit history
- changes to the readme should be backed out in favor of wiki notes if needed

Curious about:
- the `LoadLevel` bool is a bit undescriptive and I'm not sure why it was needed?
- why was `CurrentLevel` deleted from `sfx.c`?
- `music.c` could just define it's own `MAX_PATH` or be renamed to something like `MAX_SOUND_PATH`?
- why is pcmout in sound.h if it's only used in music.c?
- I think I kinda feel the same way about music_buffer_t?
- At that point I wonder if the new headers could be kept in music.c as well

Questions:
- was the sound track list generated from looking at the original cdrom audio files?
- whatever was in that google drive link seems missing now

I could use it as a great starting point if anything to build a clean branch.

Thanks for the contribution!

**Comment by chino** [comment]
Ah I believe that drive contained the pre-built vorbis files and music.dat?

Would be great if you could share that again?

I have a new branch with all the changes I was asking for above at this point where we'll be working on a clean merge:
https://github.com/ForsakenX/forsaken/pull/299

I'm going to close this to move the main work over there.

**Pull request closed without merging**
